dino_inventory/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from dino_inventory.models import User, db, check_password_hash
from dino_inventory.forms import UserLoginForm

from flask_login import login_user, logout_user, current_user, login_required


auth = Blueprint('auth', __name__, template_folder = 'auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()
    
    try:
        if request.method == "POST" and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email, password)

            user = User(email, password = password)

            db.session.add(user)
            db.session.commit()

            flash(f"You have successfully created a user account {email}", 'user-created')

            return redirect(url_for('auth.signin'))
    except:
        raise Exception('Invalid Form Data: Please Check Your Form')
    return render_template('signup.html', form=form)

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()

    try:
        if request.method == "POST" and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email, password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were successfully logged in via Email/Password', 'auth-success')
                return redirect(url_for('site.profile'))
            else:
                flash('Your Email/Password is incorrect', 'auth-failed')
                return redirect(url_for('auth.signin'))
    except:
        raise Exception('Invalid Form Data: Please Check Your Form')

    return render_template('signin.html', form=form)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))

dino_inventory/site/routes.py
from flask import Blueprint, render_template
from flask_login.utils import login_required

site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')
    

@site.route('/profile')
@login_required
def profile():
    return render_template('profile.html')
    

dino_inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Dino Park API</title>
</head>
<body>

    <!-- NavBar -->
    <nav class="navbar bg-light" id="navbar">

        <div class="container-fluid" >
            <a class="navbar-brand .text-success" href="#" id="nav-logo">
                <img src="../static/images/dino_db_logo.png" alt="" width="60" height="45" class="d-inline-block align-text-center" >
            Dino Park API
            </a>
        

            <ul class="nav justify-content-end">
                <li class="nav-item" >
                    <a class="nav-link active link" aria-current="page" href="{{ url_for('site.home') }}">Home</a>
                </li>
                {% if current_user.is_authenticated %}
                <li class="nav-item" >
                    <a class="nav-link active link" aria-current="page" href="{{ url_for('site.profile') }}">Profile</a>
                </li>
                <li class="nav-item" >
                    <a class="nav-link active link" aria-current="page" href="{{ url_for('auth.logout') }}">Log-Out</a>
                </li>
                {% else %}
                <li class="nav-item" >
                    <a class="nav-link active link" aria-current="page" href="{{ url_for('auth.signin') }}">Log-In</a>
                </li>
                <li class="nav-item" >
                    <a class="nav-link active link" aria-current="page" href="{{ url_for('auth.signup') }}">Sign-Up</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>


    {% block content %}       

    {% endblock content %}

        <!-- Footer Here -->
    <footer class="row">
        <div class="col-6">
            <img src="../static/images/dino_db_logo.png" alt="Dino Park API Logo">
        </div>
        <div class="col-6" id="footer-text">
            <h3>Our Platform</h3>
            <h5>Join Our Discord</h5>
            <h5>Donate to Our Project</h5>
            <h5>Contact Us</h5>
            <h5>Give Us Feedback</h5>
    </footer>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

dino_inventory/templates/forms.html
<!-- HTML produced by the Flask Form -->
<form method = "POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email">
            {{ form.email.label }}
            {{ form.email(class= "form-control", placeholder = "Enter email here...") }}
        </fieldset>

        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Enter password here...") }}
        </fieldset>

        <!-- Submit button -->
        {{ form.submit_button(class="btn btn-primary btn-block") }}
    </div>
</form>